In [3]:
import numpy as np

In [4]:
type([1,5,3])

list

In [5]:
arreglo_np = np.array([1,2,4])

In [6]:
type(arreglo_np)

numpy.ndarray

In [7]:
tupla_np = np.array((1,2,3,4,6))

In [8]:
type(tupla_np)

numpy.ndarray

In [9]:
np.zeros((2))

array([0., 0.])

In [10]:
np.zeros((7))

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [13]:
np.empty((3,4,5,9))

array([[[[0.00000000e+000, 8.02611839e-315, 2.02369289e-320,
                      nan, 1.12419047e-311, 1.12418770e-311,
          1.12420950e-311, 1.12422263e-311, 1.12422263e-311],
         [1.12422263e-311, 1.12422263e-311, 1.12421045e-311,
          1.12422263e-311, 1.12422263e-311, 1.12422263e-311,
          1.12422263e-311, 1.12422263e-311, 1.12422269e-311],
         [1.12422263e-311, 1.12422263e-311, 1.12422263e-311,
          1.12421047e-311, 1.12422263e-311, 1.12421052e-311,
          1.12421052e-311, 1.12421052e-311, 1.12421046e-311],
         [1.12422269e-311, 1.12421052e-311, 1.12421052e-311,
          1.12421052e-311, 1.12421052e-311, 1.12422263e-311,
          1.12422263e-311, 1.12422263e-311, 1.12422263e-311],
         [1.12422263e-311, 1.12422263e-311, 1.12421052e-311,
          1.12421052e-311, 1.12422269e-311, 1.12422264e-311,
          1.12421052e-311, 1.12422264e-311, 1.12422264e-311]],

        [[1.12422264e-311, 1.12421052e-311, 1.12421052e-311,
          1.12421

In [14]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
np.arange(3,10) 

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
arreglo_pares = np.arange(0,20,2)  
print(arreglo_pares)

[ 0  2  4  6  8 10 12 14 16 18]


In [18]:
arreglo_pares.size

10

In [19]:
arreglo_pares.shape

(10,)

In [20]:
arreglo_pares.reshape((5,2))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [21]:
np.arange(24).reshape((6,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [50]:
np.arange(100000).reshape(102000,10)

array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [99970, 99971, 99972, ..., 99977, 99978, 99979],
       [99980, 99981, 99982, ..., 99987, 99988, 99989],
       [99990, 99991, 99992, ..., 99997, 99998, 99999]])

In [55]:
np.arange(100000).reshape(10000,10)

array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [99970, 99971, 99972, ..., 99977, 99978, 99979],
       [99980, 99981, 99982, ..., 99987, 99988, 99989],
       [99990, 99991, 99992, ..., 99997, 99998, 99999]])

In [22]:
np.arange(100000).reshape(10000,10)

array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [99970, 99971, 99972, ..., 99977, 99978, 99979],
       [99980, 99981, 99982, ..., 99987, 99988, 99989],
       [99990, 99991, 99992, ..., 99997, 99998, 99999]])

In [23]:
a = np.array([10,10,10])
b = np.array((5,5,5))

In [24]:
# Suma
a + b

array([15, 15, 15])

In [25]:
# Resta
a-b

array([5, 5, 5])

In [26]:
# Multiplicacion
a * b

array([50, 50, 50])

In [27]:
# Division
a / b

array([2., 2., 2.])

In [28]:
# Division
a % b

array([0, 0, 0], dtype=int32)

In [29]:
a / 2

array([5., 5., 5.])

In [30]:
a % 2

array([0, 0, 0], dtype=int32)

In [31]:
a + 10

array([20, 20, 20])

In [32]:
a - 3

array([7, 7, 7])

In [33]:
a * 2

array([20, 20, 20])

In [34]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
arreglo_doce > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [36]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [37]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [38]:
A * B

array([[ 0,  5],
       [12, 21]])

In [39]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [40]:
RESULTADO = np.arange(4).reshape(2,2)
np.dot(A,B,RESULTADO)

array([[ 6,  7],
       [26, 31]])

In [41]:
arreglo_tres = np.arange(3) 
arreglo_tres +=2

In [42]:
arreglo_tres.sum()

9

In [43]:
arreglo_tres.min()

2

In [44]:
arreglo_tres.max()

4

In [45]:
arreglo_tres_cuatro = np.arange(24).reshape(6,2,2)
arreglo_tres_cuatro

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [46]:
arreglo_tres_cuatro.sum(axis=0)

array([[60, 66],
       [72, 78]])

In [47]:
arreglo_tres_cuatro.sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20],
       [26, 28],
       [34, 36],
       [42, 44]])

In [48]:
arreglo_tres_cuatro.sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21],
       [25, 29],
       [33, 37],
       [41, 45]])

In [49]:
arreglo_tres_cuatro.sum()

276