# Reshaping

In [1]:
import numpy as np

In [2]:
paises_uno = ('Ecuador','USA','Cuba','Venezuela')

In [3]:
paises_dos = ('Brazil','China','Japon','Mexico')

In [4]:
arreglo_paises_2d = np.array([paises_uno,paises_dos])

In [5]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [6]:
arreglo_paises_2d.shape

(2, 4)

In [7]:
 arreglo_paises_2d.flatten()

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brazil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [8]:
 arreglo_paises_2d.flatten().shape

(8,)

In [10]:
 arreglo_paises_2d.flatten().reshape(2,2,2)

array([[['Ecuador', 'USA'],
        ['Cuba', 'Venezuela']],

       [['Brazil', 'China'],
        ['Japon', 'Mexico']]], dtype='<U9')

In [11]:
arreglo_paises_2d.flatten().reshape(4,-1)  # Lo q logre llenar 

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brazil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [12]:
arreglo_paises_2d.flatten().reshape(-1,2)

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brazil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [15]:
arreglo_paises_2d.flatten().reshape(2,2,-1)

array([[['Ecuador', 'USA'],
        ['Cuba', 'Venezuela']],

       [['Brazil', 'China'],
        ['Japon', 'Mexico']]], dtype='<U9')

In [16]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [18]:
arreglo_paises_2d.T.shape

(4, 2)

In [19]:
arreglo_paises_2d.T.flatten()

array(['Ecuador', 'Brazil', 'USA', 'China', 'Cuba', 'Japon', 'Venezuela',
       'Mexico'], dtype='<U9')

In [21]:
arreglo_paises = arreglo_paises_2d.flatten()

In [22]:
arreglo_paises

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brazil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [23]:
np.split(arreglo_paises,2)

[array(['Ecuador', 'USA', 'Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brazil', 'China', 'Japon', 'Mexico'], dtype='<U9')]

In [25]:
np.split(arreglo_paises,4)

[array(['Ecuador', 'USA'], dtype='<U9'),
 array(['Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brazil', 'China'], dtype='<U9'),
 array(['Japon', 'Mexico'], dtype='<U9')]

In [26]:
arreglo = np.arange(12)

In [27]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
np.split(arreglo,2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [34]:
np.split(arreglo,[1,3,5,7,8])

[array([0]),
 array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7]),
 array([ 8,  9, 10, 11])]

In [45]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [47]:
arr1, arr2, arr3, arr4 = np.hsplit(arreglo_paises_2d,4)

In [43]:
np.split(arreglo_paises_2d,2)

[array([['Ecuador', 'USA', 'Cuba', 'Venezuela']], dtype='<U9'),
 array([['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')]

In [41]:
np.vsplit(arreglo_paises_2d,2)

[array([['Ecuador', 'USA', 'Cuba', 'Venezuela']], dtype='<U9'),
 array([['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')]

In [48]:
arr1

array([['Ecuador'],
       ['Brazil']], dtype='<U9')

In [49]:
arr2

array([['USA'],
       ['China']], dtype='<U9')

In [50]:
arr1, arr2, arr3, arr4 = np.hsplit(arreglo_paises_2d,4)

In [51]:
type(np.hsplit(arreglo_paises_2d,4))

list

In [52]:
x1,x2,x3 = [1,2,3]

In [56]:
x1 = x2 = x3 = 1


In [57]:
x1 = x1 + 1

In [58]:
x1

2

In [59]:
x2

1