# Indices

In [1]:
import numpy as np

In [2]:
numeros = np.arange(11)**2

In [3]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [7]:
indices = [2,5,7]

In [8]:
numeros[indices]

array([ 4, 25, 49], dtype=int32)

In [9]:
arreglo_frutas = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Platano','Granadilla','Sandia']
])

In [10]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [12]:
arreglo_frutas.shape

(3, 4)

In [14]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])

In [15]:
arreglo_columnas = np.array([
    [1,3],
    [1,2],
    [0,2],
])

In [16]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

array([['Manzana', 'Melon'],
       ['Uva', 'Naranja'],
       ['Frutilla', 'Granadilla']], dtype='<U10')

In [17]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [18]:
filas = np.array([
    [0,0],
    [1,1],
    [2,2]
])

In [19]:
columnas = np.array([
    [2,3],
    [2,3],
    [2,3]
])

In [20]:
arreglo_frutas[filas,columnas]

array([['Pera', 'Melon'],
       ['Naranja', 'Papaya'],
       ['Granadilla', 'Sandia']], dtype='<U10')

In [22]:
arreglo_nuevo = np.array([[
    ['Pera','Sandia','Papaya','Naranja'],
    ['Manzana','Uva','Sandia','Melon'],
    ['Platano','Frutilla','Limon','Mora']
],
[
    ['Naranjilla','Tomate','Pera','Toronja'],
    ['Granadilla','Guanabana','Durazno','Babaco'],
    ['Frambuesa','Melocoton','Claudia','Capuli']
]])

In [261]:
primera_dim = np.array([
    [0,0]
]
)

In [262]:
segunda_dim = np.array([
    [0,0],
    [1,1],
    [2,2],
])

In [263]:
tercera_dim = np.array([
    [0,3],
    [0,3],
    [0,3],
])

In [264]:
arreglo_nuevo[primera_dim,segunda_dim,tercera_dim]

array([['Pera', 'Naranja'],
       ['Manzana', 'Melon'],
       ['Platano', 'Mora']], dtype='<U10')

In [245]:
arreglo_nuevo.shape

(2, 3, 4)

In [246]:
arreglo_nuevo[1][0][0]

'Naranjilla'

In [278]:
arreglo_con_p = arreglo_nuevo

array([[[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]]])

In [299]:
con_p = list(filter(lambda x: x.startswith('P'), arreglo_nuevo.flatten()))


In [300]:
con_p

['Pera', 'Papaya', 'Platano', 'Pera']